# Generated by Django 2.2.6 on 2020-03-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200304_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='Не выбрано', on_delete=django.db.models.deletion.CASCADE, to='p_library.Publisher'),
        ),
    ]
