# Generated by Django 2.2.6 on 2020-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200324_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(to='p_library.Book'),
        ),
    ]
