# Generated by Django 2.2.6 on 2020-03-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0011_auto_20200324_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='debt',
            new_name='full_count',
        ),
    ]
