# Generated by Django 2.2.6 on 2020-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_auto_20200324_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='full_count',
            field=models.BooleanField(default=True),
        ),
    ]
