# Generated by Django 2.2.6 on 2020-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0014_auto_20200324_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(blank=True, to='p_library.Friend'),
        ),
    ]
